import type { Device } from "./types";

export const DEVICES: Device[] = [
  // ==================== MRI ====================
  {
    id: "mri-sie-magnetom-vida",
    name: "Magnetom Vida",
    vendor: "Siemens Healthineers",
    modality: "MRI",
    releaseYear: 2022,
    tagline: "3T whole-body MRI with BioMatrix patient adaptation.",
    fieldStrengthT: 3,
    boreCm: 70,
    gradientStrength: 60,
    throughputPerDay: 28,
    uptimePct: 98.4,
    setupWeeks: 14,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 145,
    budgetTier: "Premium",
    estCostUSDm: 2.6,
    roiYears: 5.5,
    costPerScanUSD: 285,
    aiCapabilities: ["Deep Resolve denoising", "AutoAlign Spine/Brain", "GoBrain protocols"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4", "IHE-RAD"],
    clinicalTags: ["oncology", "neuro", "musculoskeletal", "cardiac"],
    confidence: 92,
    sources: ["Vendor spec sheet 2023", "Internal benchmark Q4-23"],
  },
  {
    id: "mri-sie-magnetom-sola",
    name: "Magnetom Sola",
    vendor: "Siemens Healthineers",
    modality: "MRI",
    releaseYear: 2021,
    tagline: "1.5T productivity workhorse with BioMatrix.",
    fieldStrengthT: 1.5,
    boreCm: 70,
    gradientStrength: 45,
    throughputPerDay: 34,
    uptimePct: 98.1,
    setupWeeks: 10,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 110,
    budgetTier: "Mid",
    estCostUSDm: 1.4,
    roiYears: 4.2,
    costPerScanUSD: 195,
    aiCapabilities: ["Deep Resolve", "AutoCoverage"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "IHE-RAD"],
    clinicalTags: ["neuro", "musculoskeletal", "abdominal", "pediatrics"],
    confidence: 90,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "mri-ge-signa-premier",
    name: "SIGNA Premier",
    vendor: "GE HealthCare",
    modality: "MRI",
    releaseYear: 2023,
    tagline: "3T research-grade MRI with AIR Recon DL.",
    fieldStrengthT: 3,
    boreCm: 70,
    gradientStrength: 70,
    throughputPerDay: 26,
    uptimePct: 97.8,
    setupWeeks: 16,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 150,
    budgetTier: "Flagship",
    estCostUSDm: 2.9,
    roiYears: 6.0,
    costPerScanUSD: 305,
    aiCapabilities: ["AIR Recon DL", "AIR Touch coil", "SmartExam"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["neuro", "oncology", "musculoskeletal", "cardiac"],
    confidence: 91,
    sources: ["Vendor spec sheet 2023", "Peer-reviewed lit 2023"],
  },
  {
    id: "mri-ge-signa-artist",
    name: "SIGNA Artist",
    vendor: "GE HealthCare",
    modality: "MRI",
    releaseYear: 2020,
    tagline: "1.5T wide-bore for diverse patient populations.",
    fieldStrengthT: 1.5,
    boreCm: 70,
    gradientStrength: 44,
    throughputPerDay: 32,
    uptimePct: 97.5,
    setupWeeks: 11,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 105,
    budgetTier: "Mid",
    estCostUSDm: 1.3,
    roiYears: 4.5,
    costPerScanUSD: 188,
    aiCapabilities: ["AIR Recon DL", "SmartExam"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["neuro", "musculoskeletal", "abdominal", "pediatrics"],
    confidence: 88,
    sources: ["Vendor spec sheet 2021"],
  },
  {
    id: "mri-phi-ingenia-elition",
    name: "Ingenia Elition X",
    vendor: "Philips",
    modality: "MRI",
    releaseYear: 2022,
    tagline: "3T digital MRI with Compressed SENSE & SmartSpeed.",
    fieldStrengthT: 3,
    boreCm: 70,
    gradientStrength: 65,
    throughputPerDay: 30,
    uptimePct: 98.0,
    setupWeeks: 13,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 140,
    budgetTier: "Premium",
    estCostUSDm: 2.5,
    roiYears: 5.2,
    costPerScanUSD: 275,
    aiCapabilities: ["SmartSpeed", "Compressed SENSE", "VitalEye"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4", "IHE-RAD"],
    clinicalTags: ["oncology", "neuro", "cardiac", "musculoskeletal"],
    confidence: 90,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "mri-phi-mr-5300",
    name: "MR 5300",
    vendor: "Philips",
    modality: "MRI",
    releaseYear: 2022,
    tagline: "1.5T helium-free BlueSeal magnet.",
    fieldStrengthT: 1.5,
    boreCm: 70,
    gradientStrength: 45,
    throughputPerDay: 33,
    uptimePct: 98.6,
    setupWeeks: 9,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 95,
    budgetTier: "Mid",
    estCostUSDm: 1.5,
    roiYears: 4.0,
    costPerScanUSD: 180,
    aiCapabilities: ["SmartSpeed", "AutoView"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["neuro", "musculoskeletal", "abdominal", "pediatrics"],
    confidence: 89,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "mri-can-vantage-galan",
    name: "Vantage Galan 3T",
    vendor: "Canon Medical",
    modality: "MRI",
    releaseYear: 2021,
    tagline: "3T MRI with AiCE deep-learning reconstruction.",
    fieldStrengthT: 3,
    boreCm: 71,
    gradientStrength: 50,
    throughputPerDay: 27,
    uptimePct: 97.6,
    setupWeeks: 14,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 138,
    budgetTier: "Premium",
    estCostUSDm: 2.3,
    roiYears: 5.4,
    costPerScanUSD: 270,
    aiCapabilities: ["AiCE Reconstruction", "Iterative Motion Correction"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["oncology", "neuro", "musculoskeletal"],
    confidence: 86,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "mri-can-vantage-orian",
    name: "Vantage Orian 1.5T",
    vendor: "Canon Medical",
    modality: "MRI",
    releaseYear: 2020,
    tagline: "1.5T cost-efficient platform with patient comfort focus.",
    fieldStrengthT: 1.5,
    boreCm: 71,
    gradientStrength: 33,
    throughputPerDay: 30,
    uptimePct: 97.2,
    setupWeeks: 10,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 100,
    budgetTier: "Entry",
    estCostUSDm: 1.1,
    roiYears: 3.8,
    costPerScanUSD: 165,
    aiCapabilities: ["AiCE", "ForeSee View"],
    aiMaturity: 3,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["musculoskeletal", "abdominal", "pediatrics"],
    confidence: 84,
    sources: ["Vendor spec sheet 2021"],
  },

  // ==================== CT ====================
  {
    id: "ct-sie-naeotom-alpha",
    name: "NAEOTOM Alpha",
    vendor: "Siemens Healthineers",
    modality: "CT",
    releaseYear: 2022,
    tagline: "Photon-counting CT for ultra-high-resolution imaging.",
    sliceCount: 144,
    detectorRows: 120,
    rotationTimeS: 0.25,
    throughputPerDay: 70,
    uptimePct: 98.5,
    setupWeeks: 12,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 110,
    budgetTier: "Flagship",
    estCostUSDm: 2.8,
    roiYears: 5.8,
    costPerScanUSD: 145,
    aiCapabilities: ["myExam Companion", "QuantumPlus iterative recon"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4", "IHE-RAD"],
    clinicalTags: ["cardiac", "oncology", "neuro", "musculoskeletal"],
    confidence: 93,
    sources: ["Vendor spec sheet 2023", "Peer-reviewed lit 2023"],
  },
  {
    id: "ct-sie-somatom-x-cite",
    name: "SOMATOM X.cite",
    vendor: "Siemens Healthineers",
    modality: "CT",
    releaseYear: 2021,
    tagline: "Single-source 128-slice CT with myExam Companion guidance.",
    sliceCount: 128,
    detectorRows: 64,
    rotationTimeS: 0.3,
    throughputPerDay: 95,
    uptimePct: 98.2,
    setupWeeks: 8,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 90,
    budgetTier: "Premium",
    estCostUSDm: 1.6,
    roiYears: 4.2,
    costPerScanUSD: 95,
    aiCapabilities: ["myExam Companion", "ADMIRE iterative recon"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["emergency", "trauma", "abdominal", "neuro"],
    confidence: 90,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "ct-ge-revolution-apex",
    name: "Revolution Apex",
    vendor: "GE HealthCare",
    modality: "CT",
    releaseYear: 2022,
    tagline: "256-slice CT with TrueFidelity DL reconstruction.",
    sliceCount: 256,
    detectorRows: 256,
    rotationTimeS: 0.28,
    throughputPerDay: 80,
    uptimePct: 98.0,
    setupWeeks: 11,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 105,
    budgetTier: "Flagship",
    estCostUSDm: 2.4,
    roiYears: 5.0,
    costPerScanUSD: 130,
    aiCapabilities: ["TrueFidelity DL", "Smart Subscription", "Effortless Workflow"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["cardiac", "oncology", "neuro"],
    confidence: 91,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "ct-ge-revolution-maxima",
    name: "Revolution Maxima",
    vendor: "GE HealthCare",
    modality: "CT",
    releaseYear: 2020,
    tagline: "64-slice CT optimized for community hospitals.",
    sliceCount: 64,
    detectorRows: 64,
    rotationTimeS: 0.35,
    throughputPerDay: 110,
    uptimePct: 98.7,
    setupWeeks: 6,
    complexity: "Low",
    maintenanceBurden: 2,
    powerKW: 70,
    budgetTier: "Entry",
    estCostUSDm: 0.7,
    roiYears: 3.0,
    costPerScanUSD: 70,
    aiCapabilities: ["Smart MAR", "AutoPositioning"],
    aiMaturity: 3,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["emergency", "trauma", "abdominal"],
    confidence: 87,
    sources: ["Vendor spec sheet 2021"],
  },
  {
    id: "ct-phi-spectral-7500",
    name: "Spectral CT 7500",
    vendor: "Philips",
    modality: "CT",
    releaseYear: 2021,
    tagline: "Dual-layer detector spectral CT, every patient every scan.",
    sliceCount: 128,
    detectorRows: 64,
    rotationTimeS: 0.27,
    throughputPerDay: 75,
    uptimePct: 98.1,
    setupWeeks: 10,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 100,
    budgetTier: "Premium",
    estCostUSDm: 2.1,
    roiYears: 4.8,
    costPerScanUSD: 115,
    aiCapabilities: ["Precise Suite", "Spectral AI"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4", "IHE-RAD"],
    clinicalTags: ["oncology", "cardiac", "abdominal", "neuro"],
    confidence: 90,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "ct-phi-incisive",
    name: "Incisive CT",
    vendor: "Philips",
    modality: "CT",
    releaseYear: 2020,
    tagline: "AI-enabled 128-slice CT for sustainable operations.",
    sliceCount: 128,
    detectorRows: 64,
    rotationTimeS: 0.35,
    throughputPerDay: 105,
    uptimePct: 98.4,
    setupWeeks: 7,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 80,
    budgetTier: "Mid",
    estCostUSDm: 1.0,
    roiYears: 3.4,
    costPerScanUSD: 82,
    aiCapabilities: ["Precise Position", "Precise Cardiac", "iPatient"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["emergency", "trauma", "abdominal", "cardiac"],
    confidence: 88,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "ct-can-aquilion-one-prism",
    name: "Aquilion ONE / PRISM",
    vendor: "Canon Medical",
    modality: "CT",
    releaseYear: 2022,
    tagline: "320-detector wide-coverage CT with AiCE Inline.",
    sliceCount: 320,
    detectorRows: 320,
    rotationTimeS: 0.275,
    throughputPerDay: 65,
    uptimePct: 97.9,
    setupWeeks: 12,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 120,
    budgetTier: "Flagship",
    estCostUSDm: 2.7,
    roiYears: 5.6,
    costPerScanUSD: 150,
    aiCapabilities: ["AiCE Inline", "PIQE", "Auto Stroke ICH"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["cardiac", "neuro", "oncology", "emergency"],
    confidence: 91,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "ct-can-aquilion-serve",
    name: "Aquilion Serve",
    vendor: "Canon Medical",
    modality: "CT",
    releaseYear: 2021,
    tagline: "80-slice CT with INSTINX automated workflow.",
    sliceCount: 80,
    detectorRows: 80,
    rotationTimeS: 0.35,
    throughputPerDay: 100,
    uptimePct: 98.3,
    setupWeeks: 7,
    complexity: "Low",
    maintenanceBurden: 2,
    powerKW: 75,
    budgetTier: "Entry",
    estCostUSDm: 0.85,
    roiYears: 3.2,
    costPerScanUSD: 78,
    aiCapabilities: ["INSTINX", "AiCE"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["emergency", "trauma", "abdominal"],
    confidence: 86,
    sources: ["Vendor spec sheet 2022"],
  },

  // ==================== X-RAY ====================
  {
    id: "xr-sie-multix-impact",
    name: "Multix Impact",
    vendor: "Siemens Healthineers",
    modality: "X-ray",
    releaseYear: 2022,
    tagline: "Floor-mounted DR system with myExam Companion guidance.",
    throughputPerDay: 95,
    uptimePct: 99.1,
    setupWeeks: 4,
    complexity: "Low",
    maintenanceBurden: 2,
    powerKW: 12,
    budgetTier: "Entry",
    estCostUSDm: 0.18,
    roiYears: 2.4,
    costPerScanUSD: 22,
    aiCapabilities: ["myExam Companion", "Auto thorax positioning"],
    aiMaturity: 3,
    standards: ["DICOMweb", "HL7 v2", "IHE-RAD"],
    clinicalTags: ["emergency", "trauma", "musculoskeletal"],
    confidence: 89,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "xr-ge-definium-656",
    name: "Definium 656 HD",
    vendor: "GE HealthCare",
    modality: "X-ray",
    releaseYear: 2021,
    tagline: "Premium DR room with Helix workflow automation.",
    throughputPerDay: 110,
    uptimePct: 98.9,
    setupWeeks: 5,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 14,
    budgetTier: "Mid",
    estCostUSDm: 0.32,
    roiYears: 3.0,
    costPerScanUSD: 19,
    aiCapabilities: ["Helix workflow", "Critical Care Suite (Pneumothorax triage)"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["emergency", "trauma", "pediatrics"],
    confidence: 88,
    sources: ["Vendor spec sheet 2022"],
  },

  // ==================== ULTRASOUND ====================
  {
    id: "us-phi-epiq-elite",
    name: "EPIQ Elite",
    vendor: "Philips",
    modality: "Ultrasound",
    releaseYear: 2023,
    tagline: "Premium general imaging US with anatomical intelligence.",
    throughputPerDay: 28,
    uptimePct: 99.2,
    setupWeeks: 1,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 1.2,
    budgetTier: "Premium",
    estCostUSDm: 0.22,
    roiYears: 2.8,
    costPerScanUSD: 35,
    aiCapabilities: ["Anatomical Intelligence", "Auto-measure cardiac"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["cardiac", "abdominal", "vascular", "obstetrics"],
    confidence: 90,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "us-ge-logiq-e10",
    name: "LOGIQ E10",
    vendor: "GE HealthCare",
    modality: "Ultrasound",
    releaseYear: 2022,
    tagline: "Versatile premium ultrasound with cSound architecture.",
    throughputPerDay: 30,
    uptimePct: 99.0,
    setupWeeks: 1,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 1.4,
    budgetTier: "Premium",
    estCostUSDm: 0.2,
    roiYears: 2.6,
    costPerScanUSD: 32,
    aiCapabilities: ["cSound", "Auto-IMT", "B-Steer+"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["abdominal", "vascular", "musculoskeletal"],
    confidence: 88,
    sources: ["Vendor spec sheet 2022"],
  },
  {
    id: "us-can-aplio-i900",
    name: "Aplio i900 Prism",
    vendor: "Canon Medical",
    modality: "Ultrasound",
    releaseYear: 2023,
    tagline: "High-end shared-service US with iBeam+ imaging.",
    throughputPerDay: 26,
    uptimePct: 99.1,
    setupWeeks: 1,
    complexity: "Moderate",
    maintenanceBurden: 2,
    powerKW: 1.3,
    budgetTier: "Premium",
    estCostUSDm: 0.21,
    roiYears: 2.7,
    costPerScanUSD: 33,
    aiCapabilities: ["iBeam+", "Smart Sensor 3D"],
    aiMaturity: 3,
    standards: ["DICOMweb", "HL7 v2"],
    clinicalTags: ["cardiac", "obstetrics", "abdominal"],
    confidence: 86,
    sources: ["Vendor spec sheet 2023"],
  },

  // ==================== MAMMOGRAPHY ====================
  {
    id: "mg-hol-3dimensions",
    name: "3Dimensions Mammography",
    vendor: "Hologic",
    modality: "Mammography",
    releaseYear: 2022,
    tagline: "High-resolution tomosynthesis with Genius AI Detection.",
    throughputPerDay: 42,
    uptimePct: 98.7,
    setupWeeks: 6,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 7,
    budgetTier: "Premium",
    estCostUSDm: 0.45,
    roiYears: 4.0,
    costPerScanUSD: 58,
    aiCapabilities: ["Genius AI Detection", "SmartCurve paddle", "Intelligent 2D"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "IHE-MAMMO"],
    clinicalTags: ["breast", "oncology"],
    confidence: 91,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "mg-sie-mammomat-revelation",
    name: "Mammomat Revelation",
    vendor: "Siemens Healthineers",
    modality: "Mammography",
    releaseYear: 2021,
    tagline: "Wide-angle tomosynthesis with HD breast biopsy.",
    throughputPerDay: 38,
    uptimePct: 98.5,
    setupWeeks: 6,
    complexity: "Moderate",
    maintenanceBurden: 3,
    powerKW: 8,
    budgetTier: "Premium",
    estCostUSDm: 0.42,
    roiYears: 4.2,
    costPerScanUSD: 60,
    aiCapabilities: ["Insight 2D", "PRIME (low-dose)"],
    aiMaturity: 4,
    standards: ["DICOMweb", "HL7 v2", "IHE-MAMMO"],
    clinicalTags: ["breast", "oncology"],
    confidence: 89,
    sources: ["Vendor spec sheet 2022"],
  },

  // ==================== PET/CT ====================
  {
    id: "petct-sie-biograph-vision",
    name: "Biograph Vision Quadra",
    vendor: "Siemens Healthineers",
    modality: "PET/CT",
    releaseYear: 2023,
    tagline: "Long axial FOV PET/CT with industry-leading sensitivity.",
    sliceCount: 128,
    throughputPerDay: 18,
    uptimePct: 97.6,
    setupWeeks: 22,
    complexity: "High",
    maintenanceBurden: 5,
    powerKW: 175,
    budgetTier: "Flagship",
    estCostUSDm: 4.2,
    roiYears: 7.5,
    costPerScanUSD: 1450,
    aiCapabilities: ["FlowMotion Multiparametric", "OncoFreeze AI"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4", "IHE-RAD"],
    clinicalTags: ["oncology", "molecular", "neuro", "cardiac"],
    confidence: 90,
    sources: ["Vendor spec sheet 2023"],
  },
  {
    id: "petct-ge-omni-legend",
    name: "Omni Legend",
    vendor: "GE HealthCare",
    modality: "PET/CT",
    releaseYear: 2023,
    tagline: "Digital BGO PET/CT with Effortless Workflow.",
    sliceCount: 128,
    throughputPerDay: 22,
    uptimePct: 97.8,
    setupWeeks: 18,
    complexity: "High",
    maintenanceBurden: 4,
    powerKW: 160,
    budgetTier: "Premium",
    estCostUSDm: 2.6,
    roiYears: 6.2,
    costPerScanUSD: 1180,
    aiCapabilities: ["Effortless Workflow", "Precision DL recon"],
    aiMaturity: 5,
    standards: ["DICOMweb", "HL7 v2", "FHIR R4"],
    clinicalTags: ["oncology", "molecular", "cardiac"],
    confidence: 88,
    sources: ["Vendor spec sheet 2023"],
  },
];

export function getDevice(id: string) {
  return DEVICES.find((d) => d.id === id);
}

export const VENDORS: { name: string; color: string; momentum: number }[] = [
  { name: "Siemens Healthineers", color: "var(--color-chart-1)", momentum: 92 },
  { name: "GE HealthCare", color: "var(--color-chart-2)", momentum: 88 },
  { name: "Philips", color: "var(--color-chart-3)", momentum: 84 },
  { name: "Canon Medical", color: "var(--color-chart-4)", momentum: 79 },
];

export const VENDOR_FEED = [
  { vendor: "Siemens Healthineers", note: "Photon-counting CT install base crosses 200 sites globally.", time: "2h ago" },
  { vendor: "GE HealthCare", note: "AIR Recon DL extended to body imaging protocols.", time: "5h ago" },
  { vendor: "Philips", note: "BlueSeal helium-free magnet adoption rises in EMEA.", time: "11h ago" },
  { vendor: "Canon Medical", note: "Aquilion ONE / PRISM cleared for expanded cardiac protocol.", time: "1d ago" },
  { vendor: "Siemens Healthineers", note: "myExam Companion adds neuro pediatric guidance pack.", time: "1d ago" },
  { vendor: "GE HealthCare", note: "Smart Subscription model expands to mid-tier scanners.", time: "2d ago" },
];

export const MARKET_PULSE = [
  { title: "Photon-counting CT shifts the high end", body: "Detector innovation is driving renewed flagship CT investment, especially in academic centers prioritizing cardiac and oncology workflows." },
  { title: "Helium-free MRI lowers operational risk", body: "BlueSeal-class magnets are reducing siting complexity and long-term cryogen exposure for community hospitals." },
  { title: "DL reconstruction becomes table stakes", body: "AIR Recon DL, Deep Resolve, SmartSpeed, AiCE — DL recon is now table stakes across both modalities and vendors." },
  { title: "Workflow automation differentiates mid-tier", body: "Auto-positioning and protocol guidance are now the primary differentiators in the Mid budget tier across CT and MRI." },
];
