/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as JourneyDeviceIdRouteImport } from './routes/journey.$deviceId'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices.$deviceId'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyDeviceIdRoute = JourneyDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => JourneyRoute,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/roi': typeof RoiRoute
  '/saved': typeof SavedRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/journey/$deviceId': typeof JourneyDeviceIdRoute
  '/journey/': typeof JourneyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/roi': typeof RoiRoute
  '/saved': typeof SavedRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/journey/$deviceId': typeof JourneyDeviceIdRoute
  '/journey': typeof JourneyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRouteWithChildren
  '/login': typeof LoginRoute
  '/roi': typeof RoiRoute
  '/saved': typeof SavedRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/journey/$deviceId': typeof JourneyDeviceIdRoute
  '/journey/': typeof JourneyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/assistant'
    | '/compare'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/journey'
    | '/login'
    | '/roi'
    | '/saved'
    | '/devices/$deviceId'
    | '/journey/$deviceId'
    | '/journey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/assistant'
    | '/compare'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/login'
    | '/roi'
    | '/saved'
    | '/devices/$deviceId'
    | '/journey/$deviceId'
    | '/journey'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/assistant'
    | '/compare'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/journey'
    | '/login'
    | '/roi'
    | '/saved'
    | '/devices/$deviceId'
    | '/journey/$deviceId'
    | '/journey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AssistantRoute: typeof AssistantRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  InsightsRoute: typeof InsightsRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  LoginRoute: typeof LoginRoute
  RoiRoute: typeof RoiRoute
  SavedRoute: typeof SavedRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/': {
      id: '/journey/'
      path: '/'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/$deviceId': {
      id: '/journey/$deviceId'
      path: '/$deviceId'
      fullPath: '/journey/$deviceId'
      preLoaderRoute: typeof JourneyDeviceIdRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JourneyRouteChildren {
  JourneyDeviceIdRoute: typeof JourneyDeviceIdRoute
  JourneyIndexRoute: typeof JourneyIndexRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyDeviceIdRoute: JourneyDeviceIdRoute,
  JourneyIndexRoute: JourneyIndexRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AssistantRoute: AssistantRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  InsightsRoute: InsightsRoute,
  JourneyRoute: JourneyRouteWithChildren,
  LoginRoute: LoginRoute,
  RoiRoute: RoiRoute,
  SavedRoute: SavedRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
